name: Python Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r scraper/requirements.txt

      - name: Run scraper
        run: |
          python scraper/scraper.py
